config/routes.rb
Rails.application.routes.draw do

  resources :groups
  get 'pictures/create'

  devise_for :users, :path_prefix => 'account', controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # new_user_session GET      /account/users/sign_in(.:format)                     devise/sessions#new
  get '/accept_invite/:token', to: 'users#accept_invite', as: 'accept_invite'
  # get 'pages/sou_investidor', to: 'pages#investor', as: :investor

  resources :users do
    collection do
      get 'change_profile/:id', to: 'users#change_profile'
    end
  end
  resources :roles
  resources :deals
  resources :meta
  resources :image_maps
  resources :spots, only: [:create, :update, :destroy]
  resources :places, only: [:create, :update, :destroy]
  resources :contents
  resources :contacts, only: [:create, :update, :destroy]
  resources :properties do
    collection do
      get :search
      post :search, to: 'properties#search_filter'
    end
  end
  resources :messages
  resources :notes, only: [:create, :destroy]
  resources :activities, only: [:create, :destroy]
  resources :pictures, only: [:index, :create, :destroy, :update]
  resources :documents, only: [:create, :destroy, :update]
  resources :accompaniments, only: [:create, :destroy]
  resources :attachments, only: [:create, :update, :destroy]
  resources :timelines, only: [:index]
  resources :property_kinds
  resources :groups do
    collection do
      post :add_investor, to: 'groups#add_investor'
      post :invite_investor, to: 'groups#invite_investor'
      delete 'destroy_investor/:id', to: 'groups#destroy_investor'
      delete 'destroy_invite/:id', to: 'groups#destroy_invite'
    end
  end


  get 'pages/index'
  get 'pages/sobre', to: 'pages#about', as: :about
  get 'pages/sou_investidor', to: 'pages#investor', as: :investor
  get 'pages/sou_consultor', to: 'pages#realtor', as: :realtor
  get 'pages/sou_parceiro', to: 'pages#partner', as: :partner

  get 'panel/search_results', to: 'panel#search_results', as: :search_results
  get 'panel/my_clients', to: 'panel#my_clients', as: :my_clients
  get 'panel/my_contacts', to: 'panel#my_contacts', as: :my_contacts
  get 'panel/my_profile', to: 'panel#my_profile', as: :my_profile
  get 'panel/my_profile_cc/:id', to: 'panel#my_profile_cc', as: :my_profile_cc
  get 'panel/public_profile/:id', to: 'panel#public_profile', as: :public_profile
  get 'panel/add_contact', to: 'panel#add_contact', as: :add_contact
  get 'panel/edit_contact/:id', to: 'panel#edit_contact', as: :edit_contact
  get 'panel/edit_profile', to: 'panel#edit_profile', as: :edit_profile
  get 'panel/edit_profile_cc', to: 'panel#edit_profile_cc', as: :edit_profile_cc
  get 'panel/remove_contact/:id', to: 'panel#remove_contact', as: :remove_contact
  get 'panel/my_realtor', to: 'panel#my_realtor', as: :my_realtor
  get 'panel/change_realtor/:id', to: 'panel#change_realtor', as: :change_realtor
  get 'panel/customer_activities/:id', to: 'panel#customer_activities', as: :customer_activities
  get 'panel/notifications', to: 'panel#notifications', as: :notifications
  get 'panel/my_ventures', to: 'panel#my_ventures', as: :my_ventures
  get 'panel/my_deals', to: 'panel#my_deals', as: :my_deals
  get 'panel/view_docs', to: 'panel#view_docs', as: :view_docs
  get 'panel/notify_gallery', to: 'panel#notify_gallery', as: :notify_gallery
  get 'panel/change_deal_status', to: 'panel#change_deal_status', as: :change_deal_status
  get 'panel/mark_notifications_as_visualiazed', to: 'panel#mark_notifications_as_visualiazed', as: :mark_notifications_as_visualiazed
  get 'properties/change_plants_order/:id', to: 'properties#change_plants_order', as: :change_plants_order
  # get 'properties/busca', to: 'properties#index_busca', controller: 'properties'

  authenticated :user, ->(u) { u.role.name == 'admin' } do
    root "admin#index", as: :admin_root
  end

  get 'admin/manage_users', to: 'admin#manage_users', as: :manage_users
  get 'admin/configurations', to: 'admin#configurations', as: :configurations
  get 'admin/edit_pages', to: 'admin#edit_pages', as: :edit_pages
  get 'admin/update_page_attr', to: 'admin#update_page_attr', as: :update_page_attr
  get 'admin/add_page_meta_contents', to: 'admin#add_page_meta_contents', as: :add_page_meta_contents
  get 'admin/deals', to: 'admin#deals', as: :admin_deals

  authenticated :user, ->(u) { u.role.name == 'omniauth' } do
    root "panel#first_login", as: :first_login
    get 'panel/choose_role', to: 'panel#choose_role', as: :choose_role
  end

  authenticated :user do
    root 'properties#index', as: :authenticated_root
  end

  root 'pages#index'

  namespace :autocomplete, constraints: { format: :json } do
    resources :cities, only: :index
  end

  #get '*path' => redirect('/')

end

app/views/admin/_property_searchform.html.erb
<div class="searchable-wrapper">
	<form  class="searchable-form" method="get" action="<%= root_url %>">
		<input type="hidden" name="search" value="true">
		<div class="row">
			<div class="col-md-1">
				<span class="filter-by text-right">Filtrar por:</span>
			</div>
			<div class="col-md-2">
				<div class="form-group">
		            <%= select_tag( :kind, options_for_select( @kinds, params[:kind] ), { include_blank: 'Tipo', class: 's2-select', style: 'width: 100%' } ) %>
	           	</div>	
			</div>
			<div class="col-md-2">
				<div class="form-group">
		           <%= select_tag( :status, options_for_select( enum_options_for_select( Property, :status ), params[:status] ), { include_blank: 'Status', class: 's2-select', style: 'width: 100%' } ) %>
	           	</div>	
			</div>
			<div class="col-md-2">
				<div class="form-group">
		            <%= select_tag( :owner, options_for_select( @owners, params[:owner] ), { include_blank: 'Parceiro', class: 's2-select', style: 'width: 100%' } ) %>
	           	</div>	
			</div>
			<div class="col-md-4">
				<%= text_field_tag 'q', nil, placeholder: 'Buscar empreendimentos', value: params[:q] %>
				<% if params.has_key?( :q )  %>
					<p class="text-right back-inbox"><a href="<%= root_url %>"><%= fa_icon 'times' %> remover filtros</a></p>
				<% end %>
			</div>
			<div class="col-md-1">
				<%= button_tag 'Aplicar filtros', type: 'submit', class: 'btn btn-primary' %>				
			</div>
		</div>
	</form>
	<% if params.has_key?( :q )  %>
		<p class="results-for">Mostrando resultados para: <b><%= params[:q] %></b></p>
	<% end %>
</div>

app/views/admin/_user_searchform.html.erb
<div class="searchable-wrapper">
	<form  class="searchable-form" method="get" action="<%= manage_users_url %>">
		<input type="hidden" name="search" value="true">
		<div class="row">
			<div class="col-md-4">
			</div>
			<div class="col-md-1">
				<span class="filter-by text-right">Filtrar por:</span>
			</div>
			<div class="col-md-2">
				<div class="form-group">
		            <%= select_tag( :role, options_for_select( @roles, params[:role] ), { include_blank: 'Perfil', class: 's2-select', style: 'width: 100%' } ) %>
	           	</div>	
			</div>
			<div class="col-md-4">
				<%= text_field_tag 'q', nil, placeholder: 'Buscar usuários', value: params[:q] %>
				<% if params.has_key?( :q )  %>
					<p class="text-right back-inbox"><a href="<%= manage_users_url %>"><%= fa_icon 'times' %> remover filtros</a></p>
				<% end %>
			</div>
			<div class="col-md-1">
				<%= button_tag 'Aplicar filtros', type: 'submit', class: 'btn btn-primary' %>				
			</div>
		</div>
	</form>
	<% if params.has_key?( :q )  %>
		<p class="results-for">Mostrando resultados para: <b><%= params[:q] %></b></p>
	<% end %>
</div>

app/views/admin/configurations.html.erb
<div class="bg-white oportunity-resume">
	<%= hidden_field_tag :current_url, configurations_url %>
	<%= render 'layouts/counters', icon: 'building', page_title: 'Configurações' %>
	<section class="development admin-properties admin-screen">
		<div class="container large-container">
		</div>
	</section>
	<div class="container vertical-tabs">
		<div class="row">
			<div class="left-col col-xs-12 col-md-3">
				<ul class="nav nav-tabs tabs-left">
					<li class="hide"><a href="#permissions-vtab" data-toggle="tab">Permissões</a></li>
					<li class="active"><a href="#property-kinds-vtab" data-toggle="tab">Tipos de imóveis</a></li>
					<li class=""><a href="#terms-vtab" data-toggle="tab">Termos de uso</a></li>
				</ul>
			</div>
			<div class="col-xs-12 col-md-9">
				<div class="tab-content ">
					<div class="tab-pane hide" id="permissions-vtab">
						<%= render 'admin/config/manage_roles' %>
					</div>
					<div class="tab-pane active" id="property-kinds-vtab">
						<%= render 'admin/config/property_kinds' %>
					</div>
					<div class="tab-pane" id="terms-vtab">
						<%= render 'admin/config/terms' %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/deals.html.erb
<div class="bg-white my-deals admin-deals">
	<%= render 'layouts/counters', page_title: 'Negócios', icon: 'suitcase' %>
	<div class="container pdt-0 pdm-xs <%= "user-role-" + current_user.role.name %>">
		<%= render 'panel/deals_searchform' %>
		<div class="full">
			<div id="accordion" class="<%= "user-role-" + current_user.role.name %>" role="tablist" aria-multiselectable="true">
			   	<% @cards.each do |card| %>
					<%= render_slider( card, card[:template] ) %>
				<% end %>	
				<%= paginate( @cards_paginatable ) %>
			</div>		
		</div>
	</div>
</div>

app/views/admin/edit_pages.html.erb
<div class="bg-white oportunity-resume">
	<%= hidden_field_tag :current_url, edit_pages_url %>
	<%= render 'layouts/counters', icon: 'book', page_title: 'Páginas' %>
	<section class="development admin-properties admin-screen">
		<div class="container large-container">
		</div>
	</section>
	<div class="container vertical-tabs">
		<div class="row">
			<div class="left-col col-xs-12 col-sm-12 col-md-2 right-col">
	    		<ul class="admin-page-list nav nav-tabs tabs-left">
	    			<% @pages.each do |page| %>
	    				<% active = page.name == 'home' && ! params.has_key?( :page ) || params[:page] == page.name ? 'active' : ''  %>
		      			<li class="admin-page-<%= page.name %> <%= active %>"><a href="<%= edit_pages_url %>?page=<%= page.name %>"><%= page.display_name %></a></li>
		      		<% end %>
	    		</ul>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-10 left-col">
	    		<div class="tab-content">
	      			<div class="tab-pane active">
	      				<%= render 'admin/pages/edit' %>
	      			</div>
	    		</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/index.html.erb
<div class="bg-white oportunity-resume">
	<%= render 'layouts/counters', icon: 'building', page_title: 'Empreendimentos' %>
	<section class="development admin-properties admin-screen">
		<div class="container large-container">
			<div class="row">
				<div class="col-lg-12">
					<%#= render 'admin/property_searchform' %>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 text-right">
					<a href="<%= new_property_url %>" style="margin-bottom: 10px;" class="btn-success btn" data-remote="true" data-type="script" data-toggle="modal" data-target="#modal-window">Cadastrar novo</a>
				</div>
			</div>
			<div class="table-responsive">
				<table id="myTable" class="table">
					<thead>
						<tr>
							<th>Imagem</th>
							<th>Nome</th>
							<th>Tipo</th>
							<th>Status</th>
							<th>Estágio</th>
							<th>Criado por</th>
							<th>Impressões</th>
							<th>Visualizações</th>
							<th>Ações</th>
						</tr>
					</thead>
					<tbody>
						<% @properties.each do |p| %>
						<tr>
							<td>
								<%= image_tag property_cover_url( p ), class: 'img-responsive'  %>
							</td>
							<td>
								<%= p.name %>
							</td>
							<td>
								<%= p.property_kind.display_name %>
							</td>
							<td>
								<%= enum_i18n( Property, 'status', p.status ) %>
							</td>
							<td>
								<%= p.stage %>%
							</td>
							<td>
								<%= p.owner.name %>
							</td>
							<td>
								<%= p.views.count %>
							</td>
							<td>
								<%= p.single_views %>
							</td>
							<td>
								<div class="btn-group">
									<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<%= fa_icon 'cog' %> <span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li><a href="<%= property_url( p.id ) %>">Visualizar</a></li>
										<li><a href="<%= edit_property_url( p.id ) %>">Editar</a></li>
										<li><a href="#" class="admin-action" data-id="<%= p.id %>" data-action="destroyProperty">Excluir</a></li>
									</ul>
								</div>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
			<!-- <div class="property-list list-group">
			<div class="list-group-item property-list-header">
			<div class="row">
			<div class="col-sm-1">Imagem</div>
			<div class="col-sm-3">Nome</div>
			<div class="col-sm-2">Tipo</div>
			<div class="col-sm-2">Status</div>
			<div class="col-sm-1">Estágio</div>
			<div class="col-sm-2">Criado por</div>
			<div class="col-sm-1">Ações</div>
		</div>
	</div>
	<% @properties.each do |p| %>
	<div id="property-item-<%= p.id %>" class="list-group-item">
	<div class="row">
	<div class="col-sm-1 property-list-thumb">
	<%= image_tag property_cover_url( p ), class: 'img-responsive'  %>
</div>
<div class="col-sm-3">
<%= p.name %>
</div>
<div class="col-sm-2">
<%= p.property_kind.display_name %>
</div>
<div class="col-sm-2">
<%= enum_i18n( Property, 'status', p.status ) %>
</div>
<div class="col-sm-1">
<%= p.stage %>%
</div>
<div class="col-sm-2">
<%= p.owner.name %>
</div>
<div class="col-sm-1">
<div class="btn-group">
<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<%= fa_icon 'cog' %> <span class="caret"></span>
</button>
<ul class="dropdown-menu">
<li><a href="<%= property_url( p.id ) %>">Visualizar</a></li>
<li><a href="<%= edit_property_url( p.id ) %>">Editar</a></li>
<li><a href="#" class="admin-action" data-id="<%= p.id %>" data-action="destroyProperty">Excluir</a></li>
</ul>
</div>
</div>
</div>
</div>
<% end %> -->
<div class="text-center">
	<%= paginate( @properties ) %>
</div>
</div>
</div>
</section>
</div>

app/views/admin/manage_users.html.erb
<div class="bg-white oportunity-resume">
	<%= render 'layouts/counters', icon: 'users', page_title: 'Usuários' %>
	<section class="development admin-users admin-screen">
		<div class="container large-container">
			<div class="row">
				<div class="col-lg-12 text-right">
					<a href="<%= new_user_url %>" style="margin-bottom: 10px;" class="btn-success btn">Cadastrar novo</a>
				</div>
			</div>
			<div class="table-responsive">
				<table id="myTable" class="table">
					<thead>
						<tr>
							<th>Foto</th>
							<th>Nome</th>
							<th>E-mail</th>
							<th>Perfil</th>
							<th>Cidade</th>
							<th>Estado</th>
							<th>Ações</th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |u| %>
						<tr>
							<td class="property-list-thumb" style="width:20px;height:20px;">
								<%= image_tag u.avatar.url( :thumb ), class: 'img-responsive'  %>
							</td>
							<td>
								<%= u.name %>
							</td>
							<td>
								<%= u.email %>
							</td>
							<td>
								<%= u.role.display_name %>
							</td>
							<td>
								<%= u.city.name unless u.city.nil? %>
							</td>
							<td>
								<%= u.state.name unless u.state.nil? %>
							</td>
							<td>
								<div class="btn-group">
									<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<%= fa_icon 'cog' %> <span class="caret"></span>
									</button>
									<ul class="dropdown-menu">
										<li><a href="<%= user_url( u.id ) %>">Visualizar</a></li>
										<li><a href="<%= edit_user_url( u.id ) %>">Editar</a></li>
										<li><a href="#" class="admin-action" data-id="<%= u.id %>" data-action="destroyUser">Excluir</a></li>
									</ul>
								</div>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</section>
</div>