config/routes.rb
Rails.application.routes.draw do

  resources :groups
  get 'pictures/create'

  devise_for :users, :path_prefix => 'account', controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # new_user_session GET      /account/users/sign_in(.:format)                     devise/sessions#new
  get '/accept_invite/:token', to: 'users#accept_invite', as: 'accept_invite'
  # get 'pages/sou_investidor', to: 'pages#investor', as: :investor

  resources :users do
    collection do
      get 'change_profile/:id', to: 'users#change_profile'
    end
  end
  resources :roles
  resources :deals
  resources :meta
  resources :image_maps
  resources :spots, only: [:create, :update, :destroy]
  resources :places, only: [:create, :update, :destroy]
  resources :contents
  resources :contacts, only: [:create, :update, :destroy]
  resources :properties do
    collection do
      get :search
      post :search, to: 'properties#search_filter'
    end
  end
  resources :messages
  resources :notes, only: [:create, :destroy]
  resources :activities, only: [:create, :destroy]
  resources :pictures, only: [:index, :create, :destroy, :update]
  resources :documents, only: [:create, :destroy, :update]
  resources :accompaniments, only: [:create, :destroy]
  resources :attachments, only: [:create, :update, :destroy]
  resources :timelines, only: [:index]
  resources :property_kinds
  resources :groups do
    collection do
      post :add_investor, to: 'groups#add_investor'
      post :invite_investor, to: 'groups#invite_investor'
      delete 'destroy_investor/:id', to: 'groups#destroy_investor'
      delete 'destroy_invite/:id', to: 'groups#destroy_invite'
    end
  end


  get 'pages/index'
  get 'pages/sobre', to: 'pages#about', as: :about
  get 'pages/sou_investidor', to: 'pages#investor', as: :investor
  get 'pages/sou_consultor', to: 'pages#realtor', as: :realtor
  get 'pages/sou_parceiro', to: 'pages#partner', as: :partner

  get 'panel/search_results', to: 'panel#search_results', as: :search_results
  get 'panel/my_clients', to: 'panel#my_clients', as: :my_clients
  get 'panel/my_contacts', to: 'panel#my_contacts', as: :my_contacts
  get 'panel/my_profile', to: 'panel#my_profile', as: :my_profile
  get 'panel/my_profile_cc/:id', to: 'panel#my_profile_cc', as: :my_profile_cc
  get 'panel/public_profile/:id', to: 'panel#public_profile', as: :public_profile
  get 'panel/add_contact', to: 'panel#add_contact', as: :add_contact
  get 'panel/edit_contact/:id', to: 'panel#edit_contact', as: :edit_contact
  get 'panel/edit_profile', to: 'panel#edit_profile', as: :edit_profile
  get 'panel/edit_profile_cc', to: 'panel#edit_profile_cc', as: :edit_profile_cc
  get 'panel/remove_contact/:id', to: 'panel#remove_contact', as: :remove_contact
  get 'panel/my_realtor', to: 'panel#my_realtor', as: :my_realtor
  get 'panel/change_realtor/:id', to: 'panel#change_realtor', as: :change_realtor
  get 'panel/customer_activities/:id', to: 'panel#customer_activities', as: :customer_activities
  get 'panel/notifications', to: 'panel#notifications', as: :notifications
  get 'panel/my_ventures', to: 'panel#my_ventures', as: :my_ventures
  get 'panel/my_deals', to: 'panel#my_deals', as: :my_deals
  get 'panel/view_docs', to: 'panel#view_docs', as: :view_docs
  get 'panel/notify_gallery', to: 'panel#notify_gallery', as: :notify_gallery
  get 'panel/change_deal_status', to: 'panel#change_deal_status', as: :change_deal_status
  get 'panel/mark_notifications_as_visualiazed', to: 'panel#mark_notifications_as_visualiazed', as: :mark_notifications_as_visualiazed
  get 'properties/change_plants_order/:id', to: 'properties#change_plants_order', as: :change_plants_order
  # get 'properties/busca', to: 'properties#index_busca', controller: 'properties'

  authenticated :user, ->(u) { u.role.name == 'admin' } do
    root "admin#index", as: :admin_root
  end

  get 'admin/manage_users', to: 'admin#manage_users', as: :manage_users
  get 'admin/configurations', to: 'admin#configurations', as: :configurations
  get 'admin/edit_pages', to: 'admin#edit_pages', as: :edit_pages
  get 'admin/update_page_attr', to: 'admin#update_page_attr', as: :update_page_attr
  get 'admin/add_page_meta_contents', to: 'admin#add_page_meta_contents', as: :add_page_meta_contents
  get 'admin/deals', to: 'admin#deals', as: :admin_deals

  authenticated :user, ->(u) { u.role.name == 'omniauth' } do
    root "panel#first_login", as: :first_login
    get 'panel/choose_role', to: 'panel#choose_role', as: :choose_role
  end

  authenticated :user do
    root 'properties#index', as: :authenticated_root
  end

  root 'pages#index'

  namespace :autocomplete, constraints: { format: :json } do
    resources :cities, only: :index
  end

  #get '*path' => redirect('/')

end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :property
  belongs_to :user

  has_many :groups_user, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :require_permission

  def require_permission
		unless current_user_has_role?( 'construction_company' )
      redirect_to '/'
		end
	end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    puts params.inspect
    investors_group =  @group.groups_user.collect {|u| u.user_id}
    @tab = 'membros'
    @tab = params['tab'] unless params['tab'].nil?
    @investors = User.investors
    @investors = @investors.where("id not in(?)", investors_group) unless investors_group.blank?
    @invites = Invite.where(group_id: @group.id)
  end

  # GET /groups/new
  def new
    @user_id = current_user.id
    @group = Group.new
    @properties = Property.where(user_id: @user_id)
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    # @investors = User.investors

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to '/panel/my_ventures', notice: 'Grupo excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  def add_investor
    @group = Group.find(params['group_id'])
    @group.groups_user.new(user_id: params['investor_id'])
    accompaniment_exists = Accompaniment.where(property_id: @group.property.id, user_id: params['investor_id']).count > 0
    accompaniment = Accompaniment.new(property_id: @group.property.id, user_id: params['investor_id'])

    respond_to do |format|
      if @group.save
        unless accompaniment_exists
          accompaniment.save
        end
        format.html { redirect_to group_url(@group.id) + "?tab=membros", notice: 'Investidor adicionado com sucesso.', tab: 'membros' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :show }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def invite_investor
    @group = Group.find(params['group_id'])
    token = Invite.generate_token
    @invite = Invite.new(name: params[:name], email: params[:email],
      group_id: @group.id, token: token)

    respond_to do |format|
      if @invite.save
        format.html { redirect_to group_url(@group.id) + "?tab=convidados", notice: 'Convite enviado com sucesso.', tab: 'convidados' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :show }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_investor
    @group_user = GroupsUser.find(params['id'])
    @group = @group_user.group
    accompaniment = Accompaniment.where(property_id: @group.property.id, user_id: @group_user.user.id)

    respond_to do |format|
      if @group_user.destroy
        if accompaniment.count > 0
          accompaniment.first.destroy
        end
        format.html { redirect_to group_url(@group.id) + "?tab=membros", notice: 'Investidor excluído com sucesso.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :show }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_invite
    @invite = Invite.find(params[:id])
    @group = Group.find(@invite.group_id)

    respond_to do |format|
      if @invite.destroy
        format.html { redirect_to group_url(@group.id) + "?tab=convidados", notice: 'Convite excluído com sucesso.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :show }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :property_id, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_add_form.html.erb
<div class="col-md-12">
  <%= form_tag('/groups/add_investor', method: :post) do %>
  <%= hidden_field_tag 'group_id', @group.id %>
  <div class="form-group">
    <label for="investor_id">Investidor</label>
    <%= select_tag( :investor_id, options_for_select(@investors.collect { |investor| [investor.name, investor.id] }),
    { prompt: 'Selecione um Investidor', class: "form-control s2-select", id: 'investor_id', required: ''  }) %>
  </div>

    <br><br>

    <button type="submit" name="button" id="add_investor" class="btn btn-provizio"><%= fa_icon 'plus' %> Adicionar Investidor ao grupo</button>
    <br><br>
  <% end %>
</div>
<div class="col-md-12">
  <table class="table table-bordered">
    <tbody class='investors'>
      <% @group.groups_user.each do |group_user| %>
        <tr>
          <td class="col-md-10"><%= group_user.user.name %></td>
          <td class="col-md-2 text-center">
            <%= form_tag("/groups/destroy_investor/#{group_user.id}", method: :delete) do %>
              <button type="submit" name="button" class="btn btn-danger"><%= fa_icon 'trash' %></button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <div class="col-md-8 col-md-offset-2" style="margin-top: 20px;">
    <div class="form-group">
      <%= f.label 'Nome do grupo' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label 'Empreendimento' %>
      <% if controller.action_name == 'edit' %>
      <span class='form-control'>
        <%= group.property.name %>
      </span>
      <% else %>
        <%= f.select :property_id, @properties.collect { |property| [property.name, property.id] }, {}, {class: 'form-control s2-select', required: ''} %>
      <% end %>
    </div>
    <div class="form-group col-md-4 col-md-offset-4 col-xs-12 col-xs-offset-2">
      <div class="row text-center">
        <div class="col-md-4 col-xs-4">
          <a href="/panel/my_ventures" class="btn btn-warning">Voltar</a>
        </div>
        <div class="col-md-4 col-xs-4">
        <% if controller.action_name == 'edit' %>
          <%= f.submit 'Atualizar', class: 'btn btn-success'%>
        <% else %>
          <%= f.submit 'Criar', class: 'btn btn-success'%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/_investor_group.html.erb
<tr>
  <td><%= @investor.name %></td>
</tr>

app/views/groups/_invite_form.html.erb
<div class="col-md-12">
  <%= form_tag('/groups/invite_investor', method: :post) do %>
    <%= hidden_field_tag 'group_id', @group.id %>
    <div class="form-group">
      <label for="name">Nome</label>
      <%= text_field_tag 'name', nil, {placeholder: 'Nome'} %>
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <%= text_field_tag 'email', nil, {placeholder: 'Email'} %>
    </div>
    <br><br>

    <button type="submit" name="button" id="add_investor" class="btn btn-provizio"><%= fa_icon 'plus' %> Convidar ao grupo</button>
    <br><br>
  <% end %>
</div>
<div class="col-md-12">
  <table class="table table-bordered">
    <tbody class='investors'>
      <% @invites.each do |invite| %>
        <tr>
          <td class="col-md-5"><%= invite.name %></td>
          <td class="col-md-5"><%= invite.email %></td>
          <td class="col-md-2 text-center">
            <%= form_tag("/groups/destroy_invite/#{invite.id}", method: :delete) do %>
              <button type="submit" name="button" class="btn btn-danger"><%= fa_icon 'trash' %></button>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/edit.html.erb
<div class="bg-white">
    <%= render 'layouts/counters', page_title: 'Acompanhamento', icon: 'line-chart' %>
    <section class="development">
      <%= render 'form', group: @group %>
    <section>
</div>

app/views/groups/index.html.erb
<div class="bg-white oportunity-resume">
  <%= render 'layouts/counters', icon: current_user_has_role?( 'construction_company' ) ? 'building' : 'binoculars', page_title: current_user_has_role?( 'construction_company' ) ? 'Empreendimentos' : 'Oportunidades' %>
  <section class="development">
    <div class="container">
      <!-- <p id="notice"><%= notice %></p> -->
      <div class="row text-center">
        <div class="col-md-12 title-group text-center">
          <%= fa_icon 'users' %>   Groupos de Investidores 
        </div>
      </div>


      <% @groups.each do |group| %>

      <%= group.name %>
      <%= group.property %>
      <%= group.user %>
      <%= link_to 'Show', group %>
      <%= link_to 'Edit', edit_group_path(group) %>
      <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %>

      <% end %>
    </div>
  </section>
  </div

  <%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<div class="bg-white">
  <%= render 'layouts/counters', page_title: 'Acompanhamento', icon: 'line-chart' %>
  <section class="development">
    <div class="container">

      <div class="col-md-12 title-group text-center">
        <%= fa_icon 'users' %>   Criar Novo Grupo
      </div>
      <br>
      <br>

      <%= render 'form', group: @group %>
    </div>
  <section>
</div>

app/views/groups/show.html.erb
<div class="bg-white">
  <%= render 'layouts/counters', page_title: 'Acompanhamento', icon: 'line-chart' %>
  <section class="development">
    <div class="container">
      <div class="investors">
        <div class="panel panel-provizio">
          <div class="panel-heading">
            <div class="panel-title text-center">
              <%= "#{@group.name}/#{@group.property.name}" %>
            </div>
          </div>
          <div class="panel-body">
            <ul class="nav nav-tabs nav-group">
              <li class="nav-item <%= @tab == 'membros' ? 'active' : '' %>">
                <a class="nav-link link-tab-group" data-toggle="tab" href="#add">Membros</a>
              </li>
              <li class="nav-item link-tab-group <%= @tab == 'convidados' ? 'active' : '' %>">
                <a class="nav-link" data-toggle="tab" href="#invite">Convidados</a>
              </li>
            </ul>
            <div class="tab-content tab-group">
              <div id="add" class="tab-pane fade in <%= @tab == 'membros' ? 'active' : '' %>">
                <%= render partial: 'groups/add_form' %>
              </div>
              <div id="invite" class="tab-pane fade in <%= @tab == 'convidados' ? 'active' : '' %>">
                <%= render partial: 'groups/invite_form' %>
              </div>
            </div>

          </div>
        </div>
        <div class="row text-center">
          <%= form_tag("/groups/#{@group.id}", method: :delete) do %>
          <a href="/panel/my_ventures" class="btn btn-provizio">Voltar</a>
          <a href="<%= "/groups/#{@group.id}/edit" %>" class="btn btn-warning">Editar</a>
          <button type="submit" name="button" class="btn btn-danger">Excluir Grupo</button>
          <% end %>
        </div>
      </div>
    </div>
    <section>
    </div>