config/routes.rb
Rails.application.routes.draw do

  resources :groups
  get 'pictures/create'

  devise_for :users, :path_prefix => 'account', controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # new_user_session GET      /account/users/sign_in(.:format)                     devise/sessions#new
  get '/accept_invite/:token', to: 'users#accept_invite', as: 'accept_invite'
  # get 'pages/sou_investidor', to: 'pages#investor', as: :investor

  resources :users do
    collection do
      get 'change_profile/:id', to: 'users#change_profile'
    end
  end
  resources :roles
  resources :deals
  resources :meta
  resources :image_maps
  resources :spots, only: [:create, :update, :destroy]
  resources :places, only: [:create, :update, :destroy]
  resources :contents
  resources :contacts, only: [:create, :update, :destroy]
  resources :properties do
    collection do
      get :search
      post :search, to: 'properties#search_filter'
    end
  end
  resources :messages
  resources :notes, only: [:create, :destroy]
  resources :activities, only: [:create, :destroy]
  resources :pictures, only: [:index, :create, :destroy, :update]
  resources :documents, only: [:create, :destroy, :update]
  resources :accompaniments, only: [:create, :destroy]
  resources :attachments, only: [:create, :update, :destroy]
  resources :timelines, only: [:index]
  resources :property_kinds
  resources :groups do
    collection do
      post :add_investor, to: 'groups#add_investor'
      post :invite_investor, to: 'groups#invite_investor'
      delete 'destroy_investor/:id', to: 'groups#destroy_investor'
      delete 'destroy_invite/:id', to: 'groups#destroy_invite'
    end
  end


  get 'pages/index'
  get 'pages/sobre', to: 'pages#about', as: :about
  get 'pages/sou_investidor', to: 'pages#investor', as: :investor
  get 'pages/sou_consultor', to: 'pages#realtor', as: :realtor
  get 'pages/sou_parceiro', to: 'pages#partner', as: :partner

  get 'panel/search_results', to: 'panel#search_results', as: :search_results
  get 'panel/my_clients', to: 'panel#my_clients', as: :my_clients
  get 'panel/my_contacts', to: 'panel#my_contacts', as: :my_contacts
  get 'panel/my_profile', to: 'panel#my_profile', as: :my_profile
  get 'panel/my_profile_cc/:id', to: 'panel#my_profile_cc', as: :my_profile_cc
  get 'panel/public_profile/:id', to: 'panel#public_profile', as: :public_profile
  get 'panel/add_contact', to: 'panel#add_contact', as: :add_contact
  get 'panel/edit_contact/:id', to: 'panel#edit_contact', as: :edit_contact
  get 'panel/edit_profile', to: 'panel#edit_profile', as: :edit_profile
  get 'panel/edit_profile_cc', to: 'panel#edit_profile_cc', as: :edit_profile_cc
  get 'panel/remove_contact/:id', to: 'panel#remove_contact', as: :remove_contact
  get 'panel/my_realtor', to: 'panel#my_realtor', as: :my_realtor
  get 'panel/change_realtor/:id', to: 'panel#change_realtor', as: :change_realtor
  get 'panel/customer_activities/:id', to: 'panel#customer_activities', as: :customer_activities
  get 'panel/notifications', to: 'panel#notifications', as: :notifications
  get 'panel/my_ventures', to: 'panel#my_ventures', as: :my_ventures
  get 'panel/my_deals', to: 'panel#my_deals', as: :my_deals
  get 'panel/view_docs', to: 'panel#view_docs', as: :view_docs
  get 'panel/notify_gallery', to: 'panel#notify_gallery', as: :notify_gallery
  get 'panel/change_deal_status', to: 'panel#change_deal_status', as: :change_deal_status
  get 'panel/mark_notifications_as_visualiazed', to: 'panel#mark_notifications_as_visualiazed', as: :mark_notifications_as_visualiazed
  get 'properties/change_plants_order/:id', to: 'properties#change_plants_order', as: :change_plants_order
  # get 'properties/busca', to: 'properties#index_busca', controller: 'properties'

  authenticated :user, ->(u) { u.role.name == 'admin' } do
    root "admin#index", as: :admin_root
  end

  get 'admin/manage_users', to: 'admin#manage_users', as: :manage_users
  get 'admin/configurations', to: 'admin#configurations', as: :configurations
  get 'admin/edit_pages', to: 'admin#edit_pages', as: :edit_pages
  get 'admin/update_page_attr', to: 'admin#update_page_attr', as: :update_page_attr
  get 'admin/add_page_meta_contents', to: 'admin#add_page_meta_contents', as: :add_page_meta_contents
  get 'admin/deals', to: 'admin#deals', as: :admin_deals

  authenticated :user, ->(u) { u.role.name == 'omniauth' } do
    root "panel#first_login", as: :first_login
    get 'panel/choose_role', to: 'panel#choose_role', as: :choose_role
  end

  authenticated :user do
    root 'properties#index', as: :authenticated_root
  end

  root 'pages#index'

  namespace :autocomplete, constraints: { format: :json } do
    resources :cities, only: :index
  end

  #get '*path' => redirect('/')

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

	helper UsersHelper
	helper PropertiesHelper
	helper EnumI18nHelper

	before_action :add_data, :authenticate_user!
	before_filter :require_permission, only: :edit

	def add_data
		@map_api_key = 'AIzaSyC-jjFQQSwpaeLKD2njDbIbUETRYnrYNl0'
		@reservation_times = [3,5,7]
	end

	def require_permission
		if current_user_has_role?( 'admin' )
			return
		end
		if current_user.id != Property.find( params[:id] ).user_id
			redirect_to root_path
		end
	end

	def index
		@sliders = []
		query_limit = params.has_key?( :filter_by ) ? 999999 : 10
		case current_user.role.name
		when 'realtor'
			#Pré lançamentos
			slide = {
				name: 'stage_0',
				title: 'Pré-lançamentos',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			if params.has_key?( :q )
				properties = Property.where( visibility: 'visible', status: 'available', stage: 0 ).search( params[:q] ).order( 'id desc' )
			else
				properties = Property.where( visibility: 'visible', status: 'available', stage: 0 ).order( 'id desc' ).limit( query_limit )
			end
			properties.each do |property|
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
				slide[:items].push({
					id: property.id,
					name: property.name,
					stage: property.stage,
					stage_percent: "#{property.stage}%",
					image_src: image,
					following: ! accompaniment.nil?,
					accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
					user_src: '',
					url: property_path( property.id ),
					edit_url: edit_property_path( property.id )
				})
			end
			@sliders.push( slide )
			#Em andamento
			slide = {
				name: 'stage_1_99',
				title: 'Em andamento',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			if params.has_key?( :q )
				properties = Property.where( visibility: 'visible', status: 'available', stage: 1..99 ).search( params[:q] ).order( 'id desc' )
			else
				properties = Property.where( visibility: 'visible', status: 'available', stage: 1..99 ).order( 'id desc' ).limit( query_limit )
			end
			properties.each do |property|
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
				slide[:items].push({
					id: property.id,
					name: property.name,
					stage: property.stage,
					stage_percent: "#{property.stage}%",
					image_src: image,
					following: ! accompaniment.nil?,
					accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
					user_src: '',
					url: property_path( property.id ),
					edit_url: edit_property_path( property.id )
				})
			end
			@sliders.push( slide )
			#Prontos para morar
			slide = {
				name: 'stage_100',
				title: 'Prontos para morar',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			if params.has_key?( :q )
				properties = Property.where( visibility: 'visible', status: 'available', stage: 100 ).search( params[:q] ).order( 'id desc' )
			else
				properties = Property.where( visibility: 'visible', status: 'available', stage: 100 ).order( 'id desc' ).limit( query_limit )
			end
			properties.each do |property|
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
				slide[:items].push({
					id: property.id,
					name: property.name,
					stage: property.stage,
					stage_percent: "#{property.stage}%",
					image_src: image,
					following: ! accompaniment.nil?,
					accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
					user_src: '',
					url: property_path( property.id ),
					edit_url: edit_property_path( property.id )
				})
			end
			@sliders.push( slide )
			#Favoritos
			slide = {
				name: 'favourites',
				title: 'Favoritos',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			Accompaniment.where( user_id: current_user.id ).each do |accompaniment|
				property = Property.find( accompaniment.property_id )
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
				slide[:items].push({
					id: property.id,
					name: property.name,
					stage: property.stage,
					stage_percent: "#{property.stage}%",
					image_src: image,
					following: ! accompaniment.nil?,
					accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
					user_src: '',
					url: property_path( property.id ),
					edit_url: edit_property_path( property.id )
				})
			end
			@sliders.push( slide )
			slide = {
				name: 'my_customers',
				title: 'Meus clientes',
				title_link: '',
				follow_button: false,
				progress_bar: false,
				can_edit: false,
				show_user: false,
				items: []
			}
			RealtorCustomer.where( user_id: current_user.id ).each do |c|
				user = User.find( c.customer_id )
				slide[:items].push({
					id: user.id,
					name: user.name,
					stage: 0,
					stage_percent: "0%",
					image_src: user.avatar? ? user.url( :thumb ) : self.helpers.missing_avatar_url,
					following: 0,
					accompaniment_id: '',
					user_src: '',
					url: customer_activities_url( user.id ),
					edit_url: ''
				})
			end
			@sliders.push( slide )
		when '_realtor'
			slide = {
				name: 'oportunities',
				title: 'Oportunidades',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			if params.has_key?( :q )
				properties = Property.where( visibility: 'visible', status: 'available' ).search( params[:q] ).order( 'id desc' )
			else
				properties = Property.where( visibility: 'visible', status: 'available' ).order( 'id desc' ).limit( query_limit )
			end
			properties.each do |property|
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
				slide[:items].push({
					id: property.id,
					name: property.name,
					stage: property.stage,
					stage_percent: "#{property.stage}%",
					image_src: image,
					following: ! accompaniment.nil?,
					accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
					user_src: '',
					url: property_path( property.id ),
					edit_url: edit_property_path( property.id )
				})
			end
			@sliders.push( slide )
			Deal.statuses.each_with_index do |status, index|
				slide = {
					name: 'status_' + status[0],
					title: self.helpers.enum_i18n( Deal, 'status', status[0] ),
					title_link: '',
					follow_button: false,
					progress_bar: true,
					can_edit: false,
					show_user: true,
					items: []
				}
				Deal.where( dealer_id: current_user.id, status: status[0] ).each do |deal|
					property = Property.find( deal.property_id )
					image = property.pictures.find_by_kind( :cover )
					image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
					accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first
					slide[:items].push({
						id: property.id,
						name: property.name,
						stage: property.stage,
						stage_percent: "#{property.stage}%",
						image_src: image,
						following: ! accompaniment.nil?,
						accompaniment_id: accompaniment.nil? ? '' : accompaniment.id,
						user_src: deal.customer.avatar? ? deal.customer.url( :thumb ) : self.helpers.missing_avatar_url,
						url: property_path( property.id ),
						edit_url: edit_property_path( property.id )
					})
				end
				@sliders.push( slide )
			end
			slide = {
				name: 'my_customers',
				title: 'Meus clientes',
				title_link: '',
				follow_button: false,
				progress_bar: false,
				can_edit: false,
				show_user: false,
				items: []
			}
			RealtorCustomer.where( user_id: current_user.id ).each do |c|
				user = User.find( c.customer_id )
				slide[:items].push({
					id: user.id,
					name: user.name,
					stage: 0,
					stage_percent: "0%",
					image_src: user.avatar? ? user.url( :thumb ) : self.helpers.missing_avatar_url,
					following: 0,
					accompaniment_id: '',
					user_src: '',
					url: customer_activities_url( user.id ),
					edit_url: ''
				})
			end
			@sliders.push( slide )
		when 'investor'
			#Pré lançamentos
			slide = {
				name: 'stage_0',
				title: 'Pré-lançamentos',
				title_link: '',
				follow_button: true,
				progress_bar: true,
				can_edit: false,
				show_user: false,
				items: []
			}
			if params.has_key?( :q )
				properties = Property.where( visibility: 'visible', status: 'available', stage: 0 ).search( params[:q] ).order( 'id desc' )
			else
				properties = Property.where( visibility: 'visible', status: 'available', stage: 0 ).order( 'id desc' ).limit( query_limit )
			end
			properties.each do |property|
				image = property.pictures.find_by_kind( :cover )
				image = image.nil? ? self.helpers.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
				accompaniment = Accompaniment.where( user_id: current_user.id, property_id: property.id ).first

app/helpers/properties_helper.rb
module PropertiesHelper
	def render_slider( slider, template = 'slider' )
		slides_html = ''
		ac = ActionController::Base.new()
		slider_item_template = template == 'table' ? 'table_row' : 'slider_item'
		slider_template = ac.render_to_string :partial => "properties/templates/#{template}"
		slider_item_template = ac.render_to_string :partial => "properties/templates/#{slider_item_template}"
		slider[:items].each do |slide|
			slides_html+= slider_item_template % slide
		end
		replaces = slider
		replaces[:slides] = slides_html.html_safe
		#replaces[:items] = replaces[:items].length
		replaces[:more_button_url] = root_url + "?filter_by=#{slider[:name]}"
		slider_template % replaces
	end
	def render_gallery_item( picture, action, group = 'gallery' )
		ac = ActionController::Base.new()
		template = ac.render_to_string :partial => "properties/#{action}/gallery_item"
		replaces = {
			id: picture.id,
			thumb: picture.file.url( :thumb ),
			large: picture.file.url( :large ),
			label: picture.label,
			group: group
		}
		template % replaces
	end
	def property_cover_url( property )
		image = property.pictures.find_by_kind( :cover )
		image = image.nil? ? self.missing_img_url : property.pictures.find_by_kind( :cover ).file.url( :thumb )
	end
	def property_icon( property )
		case property.kind
		when 'allotment'
			return 'tree'
		when 'house'
			return 'home'
		when 'apartment'
			return 'building-o'
		when 'condominium'
			return 'building'
		when 'comercial_room'
			return 'credit-card'
		when 'terrain'
			return 'road'
		end
	end
	def missing_img_url
		image_url( 'missing.png' )
	end
	def image_menu( image_name, alt, controller, action = nil )
		if action.nil?
			sufix = controller?( controller ) ? '-ativo' : ''
		else
			sufix = controller?( controller ) && action?( action ) ? '-ativo' : ''
		end
		image_tag image_name.gsub( /.png/, "#{sufix}.png" ), alt: alt
	end
	def currency_format(value)
		value_string = value.to_s
		array_string = value_string.reverse.scan(/\w{1,3}/)
		array_string.reverse!
		value_string = ""
		array_string.each do |centena|
			value_string << "." unless value_string.empty?
			value_string << centena.reverse
		end

		value_string = "R$ " + value_string
		return value_string
	end
end

app/views/properties/show/_actions.html.erb
<section id="property-actions" class="property-section property-actions text-center">
	<button class="action-button" data-action="follow" data-following="<%= ! @accompaniment.nil? %>" data-accompaniment-id="<%= @accompaniment.id unless @accompaniment.nil? %>">
		<%= fa_icon 'share' %>
		<span class="text"></span>
	</button>
	<% if current_user_has_role?( 'realtor' ) %>
		<a class="action-button hide" href="<%= messages_path %>?property_id=<%= @property.id %>&mail_template=send" data-action="sendmail">
			<%= fa_icon 'arrow-up' %>
			<span class="text"></span>
		</a>
		<a href="<%= new_deal_url %>?property_id=<%= @property.id %>" class="action-button" data-action="proposal" data-remote="true" data-type="script" data-toggle="modal" data-target="#modal-window">
			<%= fa_icon 'arrow-up' %>
			<span class="text"></span>
		</a>
	<% end %>
	<% if current_user_has_role?( 'investor' ) %>
		<a class="action-button hide" href="<%= messages_path %>?property_id=<%= @property.id %>&mail_template=proposal" data-action="proposal">
			<%= fa_icon 'arrow-up' %>
			<span class="text"></span>
		</a>
		<a href="<%= new_deal_url %>?property_id=<%= @property.id %>" class="action-button" data-action="proposal" data-remote="true" data-type="script" data-toggle="modal" data-target="#modal-window">
			<%= fa_icon 'arrow-up' %>
			<span class="text"></span>
		</a>
		<a href="https://api.whatsapp.com/send?text=Acesse:-<%= property_url(@property) %>" class="action-button" data-action="whatsapp">
			<%= fa_icon 'whatsapp' %>
			<span class="text"></span>
		</a>
	<% end %>
</div>

app/views/properties/show/_footer.html.erb
<section id="property-footer" class="property-section property-footer">
	<div class="container pdt-0">
		<p class="ft-14">*A Provizio não se responsabiliza pelo conteúdo das publicações deste site.</p>
	</div>
</section>

app/views/properties/show/_gallery.html.erb
<section class="property-section">
	<% background_image = @property.pictures.find_by_kind( :cover ).nil? ? '' : "background-image: url(#{@property.pictures.find_by_kind( :cover ).file.url(:large)}"  %>
	<div id="property-banner" class="property-banner dropzone-banner" style="<%= background_image %>"></div>
</section>
<section id="property-gallery" class="property-section">
	<div class="container">
		<div id="property-show-gallery">
			<div class="property-slider">
				<% if @gallery_count > 0 %>
					<% @gallery.each do |picture| %>
						<%= render_gallery_item( picture, :show ) %>
					<% end %>
				<% end %>
			</div>
		</div>
		<div class="grafic">
            <div id="stage-circle-small" class="ct-mg stage-circle-small"></div>
        </div>					
	</div>
</section>

app/views/properties/show/_gallery_item.html.erb
<div id="gallery-pic-%{id}" class="gallery-item">
	<div class="picture-container">
		<a href="%{large}" class="fresco" data-fresco-group="%{group}" data-fresco-caption="%{label}">
			<img src="%{thumb}" />
		</a>
	</div>
</div>

app/views/properties/show/_header.html.erb
<section id="property-title" class="property-section oportunity-information">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="title upper ft-30 mgt-10 ct-mg"><%= @property.name %></h1>
			</div>
		</div>
	</div>
</section>

app/views/properties/show/_info.html.erb
<section id="property-info" class="property-section bg-grey property-show">
	<div class="container">
		<div class="row row-eq-height" data-match-height>
			<div class="col-md-8 columns general-info-container" data-height-watch>
				<ul class="nav nav-tabs bg-white left list-oportunity-information big list-inline ft-20 reset">
				  	<li class="tabs-title-documents active tabs-title bb-grey">
				  		<a data-toggle="tab" href="#information" class="oportunity-information-tab-title">
				  			<%= fa_icon 'info-circle' %> <span class="textual">Informações</span>
				  		</a>
				  	</li>
				  	<li class="tabs-title-documents tabs-title bb-grey">
				  		<a data-toggle="tab" href="#doubts" class="oportunity-information-tab-title">
				  			<%= fa_icon 'question-circle' %> <span class="textual">Dúvidas</span>
				  		</a>
				  	</li>
				  	<li class="tabs-title-documents tabs-title bb-grey">
				  		<a data-toggle="tab" href="#docs" class="oportunity-information-tab-title">
				  			<%= fa_icon 'download' %> <span class="textual">Documentos</span>
				  		</a>
				  	</li>
				</ul>
				<div class="tab-content main">
				    <div id="information" role="tabpanel" class="active tab-pane oportunity-information-tab bg-white">
						<div class="tab-content pd-30 content">
				   			<%= @property.info_html %>
				   		</div>
				    </div>
				    <div id="doubts" role="tabpanel" class="tab-pane oportunity-information-tab bg-white">
				   		<div class="tab-content pd-30 content">
				   			<%= @property.doubts_html %>
				   		</div>
				    </div>
				    <div id="docs" role="tabpanel" class="tab-pane oportunity-information-tab bg-white">
				   		<div class="tab-content pd-30">
							<% if current_user_has_role?('realtor') %>
								<%= form_for( Document.new, html: { multipart: true, class: 'dropzone'} ) do |f| %>
									<%= f.hidden_field 'owner_id', value: '1'%>
									<div class="dz-message">
										<div class="text-center">
											<%= fa_icon 'download' %>
											Clique ou arraste os documentos aqui
										</div>
									</div>
									<div class="fallback">
										<%= f.file_field :file %><br>
									</div>
								<% end %>
							<% end %>

							<table class="docs-table table">
								<thead>
									<th>Nome</th>
									<th class="text-center">Tamanho</th>
									<th class="text-center">Baixar</th>
								</thead>
								<tbody class="table-stripe">
									<%
									    owners_ids = [0]
										  if current_user_has_role?('realtor')
												owners_ids.push(current_user.id)
											end
									%>
									<% @property.documents.where(owner_id: owners_ids).order(owner_id: :desc).each do |doc| %>
										<tr data-doc="<%= doc.id %>">
											<% if doc.owner_id > 0 %>
												<td><input id="doc-<%= doc.id %>" value="<%= doc.name.nil? ? doc.file_file_name : doc.name %>" class="doc-editable" placeholder="Nome do documento" data-doc="<%= doc.id %>" type="text" name="document[name]"></td>
											<% else %>
												<td><%= doc.name.nil? ? doc.file_file_name : doc.name %></td>
											<% end %>
											<td class="text-center"><%= ( ( doc.file_file_size / 1024 ) / 1 ).to_f %>KB</td>

											<td class="text-center">
												<% if doc.owner_id > 0 %>
													<button class="doc-remove" data-doc="<%= doc.id %>"><i class="fa fa-trash"></i></button>;
												<% else %>
													<a href="<%= doc.file.url %>" target="_blank">
														<%= fa_icon 'download' %>
													</a>
												<% end %>
											</td>
										</tr>
									<% end %>
								</tbody>
							</table>
				   		</div>
				    </div>
				</div>
			</div>
			<div class="col-md-4 columns price-container" data-height-watch>
				<ul class="nav nav-tabs bg-white left list-oportunity-information big list-inline ft-20 reset">
				  	<li class="active tabs-title bb-grey">
				  		<a data-toggle="tab" href="#price" class="oportunity-information-tab-title text-left">
				  			<%= fa_icon 'usd' %> <span class="textual">Valores</span>
				  		</a>
				  	</li>
				</ul>
				<div id="price" role="tabpanel" class="active tab-pane price ft-white oportunity-information-tab bg-white">
					<div class="tab-content valor">
			   			<p>A partir de</p>
			   			<div class="pdtb-10 ft-30">
			   				<div contenteditable="false" class="property-value mask-money prepend-rs"><%= @property.value %></div>
			   			</div>
			   			<div class="financiamento mgt-30 content">
			   				<%= @property.payment_conditions %>
						</div>
			   		</div>
			   	</div>
			</div>
		</div>
	</div>
</section>

app/views/properties/show/_map.html.erb
<section id="property-map" class="property-section property-map maps" data-latitude="<%= @property.latitude %>" data-longitude="<%= @property.longitude %>">
	<div id="map-container"></div>
	<div id="map-info" class="section-overlayer">
		<div class="container">
			<h2 class="titleU title-box bg-white txt-ct bb-grey ft-30">Localização</h2>
		</div>
	</div>
	<button class="map-toggle-nav">
		<%= fa_icon 'map' %>
		<%= fa_icon 'map-o' %>
	</button>
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= @map_api_key %>&callback=updateMap"></script>
</section>

app/views/properties/show/_plant_old.html.erb
<% unless @property.image_map.map_data.nil? %>
	<% background_image = @property.pictures.find_by_kind( :plant ).nil? ? nil : @property.pictures.find_by_kind( :plant ).file.url  %>
	<section id="section-plant" class="property-section plant">
		<div class="section-overlayer">
			<div class="container pd-30 pdt-0">
				<h2 class="pull-left titleU title-box bg-white txt-ct bb-grey ft-30">Planta</h2>
				<% unless background_image.nil? %>
					<a class="donwload-plant pull-right" href="<%= background_image %>" target="_blank">
						<span class="icon"><%= fa_icon 'download' %></span>
						<span class="text">Baixar planta</span>
					</a>
				<% end %>	
			</div>
		</div>
		<% unless @property.image_map.map_data.nil? %>
			<div id="image-map-pro-container"></div>
			<%= javascript_include_tag( 'js/image-map-pro.min' ) %>
			<%= hidden_field_tag :imap_data, @property.image_map.map_data %>
			<script type="text/javascript">
		        ;(function ($, window, document, undefined) {
		            $(document).ready(function() {
		            	var data = JSON.parse( $( '#imap_data' ).val() )[0];
		            	$('#image-map-pro-container').imageMapPro(data);
		            });
		        })(jQuery, window, document);
			</script>
		<% end %>
	</section>
<% end %>